services:
  - type: web
    name: addis-music-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://test-app-smoky-ten.vercel.app
